### ISSUE TITLE
java.lang.RuntimeException: Router error on network change: org.fourthline.cling.transport.RouterException: Router wasn't available exclusively after waiting 15000ms, lock failed: WriteLock

### ISSUE THREAD

**Issue by jisuz** [offbye/DroidDLNA#3]
你好，我在使用DroidDLNA的时候出现了问题
在网络断开的情况下会出现卡顿的情况，如果长时间操作的话，会出现无响应，报如下错误，想请教一下是什么问题引起的，有没有办法解决。

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in org.fourthline.cling.android.AndroidRouter$ConnectivityBroadcastReceiver@433c5928
    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:809)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5314)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.RuntimeException: Router error on network change: org.fourthline.cling.transport.RouterException: Router wasn't available exclusively after waiting 15000ms, lock failed: WriteLock
    at org.fourthline.cling.android.AndroidRouter.handleRouterExceptionOnNetworkTypeChange(AndroidRouter.java:250)
    at org.fourthline.cling.android.AndroidRouter$ConnectivityBroadcastReceiver.onReceive(AndroidRouter.java:295)
    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:794)
    ... 9 more
Caused by: org.fourthline.cling.transport.RouterException: Router wasn't available exclusively after waiting 15000ms, lock failed: WriteLock
    at org.fourthline.cling.transport.RouterImpl.lock(RouterImpl.java:497)
    at org.fourthline.cling.transport.RouterImpl.lock(RouterImpl.java:510)
    at org.fourthline.cling.android.AndroidRouter.disable(AndroidRouter.java:104)
    at org.fourthline.cling.android.AndroidRouter.onNetworkTypeChange(AndroidRouter.java:227)
    at org.fourthline.cling.android.AndroidRouter$ConnectivityBroadcastReceiver.onReceive(AndroidRouter.java:293)
    ... 10 more
java.lang.RuntimeException: Router error on network change: org.fourthline.cling.transport.RouterException: Router wasn't available exclusively after waiting 15000ms, lock failed: WriteLock
    at org.fourthline.cling.android.AndroidRouter.handleRouterExceptionOnNetworkTypeChange(AndroidRouter.java:250)
    at org.fourthline.cling.android.AndroidRouter$ConnectivityBroadcastReceiver.onReceive(AndroidRouter.java:295)
    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:794)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5314)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: org.fourthline.cling.transport.RouterException: Router wasn't available exclusively after waiting 15000ms, lock failed: WriteLock
    at org.fourthline.cling.transport.RouterImpl.lock(RouterImpl.java:497)
    at org.fourthline.cling.transport.RouterImpl.lock(RouterImpl.java:510)
    at org.fourthline.cling.android.AndroidRouter.disable(AndroidRouter.java:104)
    at org.fourthline.cling.android.AndroidRouter.onNetworkTypeChange(AndroidRouter.java:227)
    at org.fourthline.cling.android.AndroidRouter$ConnectivityBroadcastReceiver.onReceive(AndroidRouter.java:293)
    ... 10 more
org.fourthline.cling.transport.RouterException: Router wasn't available exclusively after waiting 15000ms, lock failed: WriteLock
    at org.fourthline.cling.transport.RouterImpl.lock(RouterImpl.java:497)
    at org.fourthline.cling.transport.RouterImpl.lock(RouterImpl.java:510)
    at org.fourthline.cling.android.AndroidRouter.disable(AndroidRouter.java:104)
    at org.fourthline.cling.android.AndroidRouter.onNetworkTypeChange(AndroidRouter.java:227)
    at org.fourthline.cling.android.AndroidRouter$ConnectivityBroadcastReceiver.onReceive(AndroidRouter.java:293)
    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:794)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5314)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by 1programmer2dfg3** [comment]
> Droid

请问解决了吗，我也有这个问题
